Monitoring 1
Otus-DevOps-2018-09/crzlol_microservices pull request #7
Opened 2019-02-09 14:40 UTC by crzlol

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Cоздали контейнер с Прометеусом
 - Запустили стенд, проверили мониторинг приложений
 - Создали контейнер с экспортером ноды
 - Натравили на нее Прометеус

## Как запустить проект:
 - Перейти в каталог src и выполнить
```
docker-compose up -d
```
 - Перейти в каталог monitoring/prometheus и выполнить
```
docker-compose -f docker-compose-monitoring.yml up -d
```

## Как проверить работоспособность:
 - Перейти по ссылкам http://docker-machine:9090, http://docker-machine:8080 и http://docker-machine:3000.

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2019-02-10 15:21 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Необходимо внести изменения, оставил комментарий к файлу. Возвращаю на доработку.

2019-02-10 15:21 UTC, mrgreyves commented on docker/docker-compose.yml
> +        subnet: 10.0.2.0/24
Уехала строка с обозначением сети

2019-02-11 16:41 UTC, crzlol commented on docker/docker-compose.yml
> +        subnet: 10.0.2.0/24
Пофиксил!

2019-02-11 17:06 UTC, mrgreyves requested changes
Не во всем файликах поправили =)

2019-02-11 17:06 UTC, mrgreyves commented on docker/docker-compose-monitoring.yml
> +  front_net:
И вот тут еще =)

2019-02-11 17:53 UTC, crzlol commented on docker/docker-compose-monitoring.yml
> +  front_net:
пофиксил тут и в остальных документах. Брал образец отсюда: https://docs.docker.com/compose/compose-file/, раздел IPV4_ADDRESS, IPV6_ADDRESS.
Докер этот конфигурированиям ест без проблем, линтер тоже не реагирует.

2019-02-11 18:05 UTC, mrgreyves approved these changes
UP!)

2019-02-11 18:05 UTC, mrgreyves commented on docker/docker-compose-monitoring.yml
> +  front_net:
Понял вас, я сторонник того что описание должно быть красивым, это упрощает и дальнейшее чтение =)

2019-02-11 18:06 UTC, crzlol commented
Я согласен полностью, написал просто, чтобы вы знали, откуда ноги растут - наверняка найдутся еще любители копипасты из офф доков :)

2019-02-11 18:07 UTC, merged